### ISSUE TITLE
Error with redis port : connection refused: tcp://127.0.0.1:6379

### ISSUE THREAD

**Issue by champdemars** [aaronpk/Device-Flow-Proxy-Server#1]
Hello Aaron

I tried to install your proxy on Linux, the proxy starts fine, however when I run a test with curl in order to get a device code, I am having this error, seems to be related to redis part of your code.

Do I need to install something else ?

root@kali:~/Device-Flow-Proxy-Server-master# php -S 127.0.0.1:8080 -t public
PHP 7.2.9-1 Development Server started at Wed May 22 14:29:37 2019
Listening on http://127.0.0.1:8080
Document root is /root/Device-Flow-Proxy-Server-master/public
Press Ctrl-C to quit.
[Wed May 22 14:30:24 2019] PHP Fatal error:  Uncaught Predis\Connection\ConnectionException: Connection refused [tcp://127.0.0.1:6379] in /root/Device-Flow-Proxy-Server-master/vendor/predis/predis/src/Connection/AbstractConnection.php:155
Stack trace:
#0 /root/Device-Flow-Proxy-Server-master/vendor/predis/predis/src/Connection/StreamConnection.php(128): Predis\Connection\AbstractConnection->onConnectionError('Connection refu...', 111)
#1 /root/Device-Flow-Proxy-Server-master/vendor/predis/predis/src/Connection/StreamConnection.php(178): Predis\Connection\StreamConnection->createStreamSocket(Object(Predis\Connection\Parameters), 'tcp://127.0.0.1...', 4)
#2 /root/Device-Flow-Proxy-Server-master/vendor/predis/predis/src/Connection/StreamConnection.php(100): Predis\Connection\StreamConnection->tcpStreamInitializer(Object(Predis\Connection\Parameters))
#3 /root/Device-Flow-Proxy-Server-master/vendor/predis/predis/src/Connection/AbstractConnection.php(81): Predis\Connection\StreamConnection->createResource()
#4 /root/Device-Flow-Proxy-Server-master/vendor/pre in /root/Device-Flow-Proxy-Server-master/vendor/predis/predis/src/Connection/AbstractConnection.php on line 155
[Wed May 22 14:30:24 2019] 127.0.0.1:51686 [500]: /device/code - Uncaught Predis\Connection\ConnectionException: Connection refused [tcp://127.0.0.1:6379] in /root/Device-Flow-Proxy-Server-master/vendor/predis/predis/src/Connection/AbstractConnection.php:155
Stack trace:
#0 /root/Device-Flow-Proxy-Server-master/vendor/predis/predis/src/Connection/StreamConnection.php(128): Predis\Connection\AbstractConnection->onConnectionError('Connection refu...', 111)
#1 /root/Device-Flow-Proxy-Server-master/vendor/predis/predis/src/Connection/StreamConnection.php(178): Predis\Connection\StreamConnection->createStreamSocket(Object(Predis\Connection\Parameters), 'tcp://127.0.0.1...', 4)
#2 /root/Device-Flow-Proxy-Server-master/vendor/predis/predis/src/Connection/StreamConnection.php(100): Predis\Connection\StreamConnection->tcpStreamInitializer(Object(Predis\Connection\Parameters))
#3 /root/Device-Flow-Proxy-Server-master/vendor/predis/predis/src/Connection/AbstractConnection.php(81): Predis\Connection\StreamConnection->createResource()
#4 /root/Device-Flow-Proxy-Server-master/vendor/pre in /root/Device-Flow-Proxy-Server-master/vendor/predis/predis/src/Connection/AbstractConnection.php on line 155

**Comment by champdemars** [comment]
Note: I got this error when I executed the following curl command:

curl http://localhost:8080/device/code -d client_id=XXXX

**Comment by aaronpk** [comment]
You will also need to install Redis. By default the code assumes it's running on the same machine but that can be configured in the config file.

**Comment by champdemars** [comment]
Exactly! I installed redis and now it works. Thank you!

**Comment by nickatsegment** [comment]
https://developer.okta.com/blog/2019/02/19/add-oauth-device-flow-to-any-server If redis is a requirement, you might want to update this blog post.
